### PR TITLE
Additional fan modes

### PR DESCRIPTION
**Pull request by Freddicus**
Hi - Still maintaining this? 😃 I added some code to enable toggling of circulate and follow schedule. It's not the prettiest code, but seems to work. I can publish my accessory to npm separate if you're not accepting pull requests. I've never done a PR before, so be gentle.

### CODE REVIEW

**Comment by AdeelK93** [comment]
When you toggle circulate, what are you toggling between? On = circulate (I imagine), so Off = auto? Is that right?

**Comment by Freddicus** [comment]
I don't have access to the API, so I had to make some guesses. :)

I used the concept of a momentary switch. It doesn't know anything about the state of the system. It just sends the API request with fan mode 2 (circulate) or 3 (follow schedule) in the payload.

I think it might be more useful as a separate accessory within the plugin, instead of separate service within the accessory. Harmony does something similar where you can add an off button that lives outside of the Apple TV accessory.

Edit: Additionally - HomeKit/HAP does not offer any generic multi-toggle / multi-state switches. I did a bunch of Google-foo looking into it. Alarm does expose a purpose-built multi-state switch, however, but borrowing that for fan states seemed improper, and HomeKit will render it with a siren in the Home app.

**Comment by Freddicus** [comment]
The code is a little sloppy, I know. If you don't want to accept the pull request, please close it and I will publish it separately giving this project credit just like you gave tcc-homebridge credit in your readme. Thanks!

**Comment by Freddicus** [comment]
@AdeelK93 Or anyone? Should I just publish my fork?

**Comment by Freddicus** [comment]
Closing. I'll publish and give credit.

**Comment by MarcMTLDK** [comment]
Hi guy's

I'm running the latest version of TCC-Fan and I still can't find anywhere the information to to make the mode to toggle from Circulate, Auto and so on ! Is there is location I never look at ?

Thank you in advance even if the last poste is almost two years old :-)

**Comment by Freddicus** [comment]
Hi @MarcMTLDK - my humble little flawed fork provides this. But you need to make sure it's configured.

https://github.com/Freddicus/homebridge-tcc-fan#new-in-this-fork

https://www.npmjs.com/package/homebridge-tcc-fan-plus

**Pull request closed without merging**
